### ISSUE TITLE
Code Review (now a checklist)

### ISSUE THREAD

**Issue by o11c** [alt-romes/programmer-calculator#36]
(Some edits made from the Reddit post)

* [x] `draw.c`:
   * [x] be aware that the screen can be resized
    * [x] `init_gui`. Avoid the long line. You're allowed to call `mvwprintw` more that once, you know ... Also, when you're not doing any formatting, there's `mvwaddstr` (though there is something to be said for uniformity).
    * [ ] `printbinary`: instead of numbers, I would just use the words "high" and "low" in opposite corners. Or if you keep numbers, use `63..48` instead of `64`.
        * [ ] If you aggressively eliminate whitespace (maybe change color or attributes?), `00000000_00000000__00000000_00000000___00000000_00000000__00000000_00000000` is only 75 columns.
    * [x] `sweepline`: arguments have misleading names. Some calls might be replaceable by `wclrtobot` or `werase`.
* [x] `history.c`:
    * [x] `add_to_history`:
        * [x]  resize by a multiple, not a constant, to avoid quadratic behavior
        * [x] should also not know about ncurses
        * [x] refactor out the resize logic
    * [x] `add_number_to_history`:
        * [x]  refactor out the int-to-binary conversion to a separate function (and don't use `sprintf` for single chars)
        * [x] This is an odd place to call `wrefresh`. Move it out to the main loop.
    * [x] `browsehistory`:
        * [x]  document `mode` and/or call it something else (dir, delta, ...)
        * [ ] `searchHistory` is currently hard-coded here (but possibly this should all go away in favor of readline's internal history)
            * [ ] to help avoid this kind of thing, simply refuse to have any global variables - make everything local to `main` or similar
* [x] `main.c`:
    * [x] never put `extern` in a `.c` file; move it to an appropriate header
        * [x] use the compiler options `-Werror=missing-declarations -Werror=redundant-decls` to help enforce this, and always put the corresponding header as the first include of the `.c` file. Use `static` as appropriate.
    * [x] `-h` normally means "help". Also, prefer `getopt_long`; be nice to your users
    * [x] I'm generally not happy with the whole layout of this code, so I didn't look too closely at it. There's too much duplication and mixed high-level logic with low-level logic. Now that you have something *working* consider taking a step back and thinking about how the program *should* work cleanly. I have some ideas here, but this margin is too
    * [x] don't pass magic numbers to `add_number_to_history`
    * [x] `apply_operations`: the pointer comparison `*current_op != operations` is different from every place that *sets* `*current_op = &operations[0];`. Honestly I would just use `NULL`, or if you don't like that, have a `NULL_OPERATION` constant. Note that there's currently no reason that the operations are in an array at all! (but that should be fixed, see below - but even so, it should not be exposed, which will make it easy to update)
    * [ ] `get_input`: since you're using curses already, use it. It won't have all the bugs that your code has.
* [x] `numberstack.c`:
    * [x] `create_numberstack` also needs error-checking
    * [x] refactor `resize_numberstack` so it doesn't need to know about curses. This could involve either returning NULL so the caller can deal with it, or else relying on a previously-installed `atexit` or similar hook.
* [x] `operators.c`:
    * [x] `getopcode` should be about 4 lines long - the operators are in the table!
    * [ ] I suggest implementing multi-character opcodes sooner rather than later.
    * [x] globalmask logic should probably be refactored out of every function, to do it just once in `apply_operations`
    * [x] `twos_complement` can be just `-a`.
    * [x] `sr` can be simplified if you use unsigned math (which you should, because this is UB)
    * [x] `rr` and `rl` also have UB when shift is 0.
    * [x] also, more usual names would be `ror` and `shr`
    * [ ] division and modulus:
        * [ ] keep these together
        * [ ] you need 3 versions of these: unsigned, signed following numerator, signed following denominator (different platforms historically chose different signed implementations, but later C standardized what x86 does - Python notably does the opposite)
        * [ ] division and modulus checking needs to handle the error of `globalmask / -1` for the signed versions
    * [x] output should probably be some `struct value_and_flags`, which more-cleanly handles SIGFPE but also ZF SF OF PF CF AF. Use GCC's overflow intrinsics (and other intrinsics) for some of those. Actually, possibly mask should be included as well ... this would involve masking *before* the operations as well (easy enough in `apply_operations`), and removing the whole "mask the whole history" logic.

**Comment by alt-romes** [comment]
> never put extern in a .c file; move it to an appropriate header
@o11c do you think you could enlighten me a bit more?

I did what I think is appropriate, which is to declare the global variables defined in the `c` files in their respective header files (using `extern`).

However, throughout the code before using these global variables in a `c` file we declare them as `extern` - should we declare the global variables used in a `c` file in its header? (even tho it's not the file defining them)?

**Comment by alt-romes** [comment]
Could anyone explain to me why `ror` and `rol` would have UB when shift is 0 ? (taking into consideration I've already made the `shr` have defined behaviour)

Thank you
~romes

**Comment by alt-romes** [comment]
If anyone understands these lines better, please let me know as well.

> division and modulus:
> keep these together
> you need 3 versions of these: unsigned, signed following numerator, signed following denominator (different platforms historically chose different signed implementations, but later C standardized what x86 does - Python notably does the opposite)
> division and modulus checking needs to handle the error of globalmask / -1 for the signed versions

**Comment by o11c** [comment]
So you have:

```c++
static long long rol(long long a, long long b) {

    return b << a | shr(globalmasksize-a, b);
}
```

If a is 0, that becomes:

b << 0 | shr(64-0, b)

but shifting by 64 is bigger than the type, which is UB.

For `shr`, hardware generally does one of:

* produce 0 (or possibly -1 for signed right shift). This is the "obvious" result, and was common when shifters were implemented as a loop because hardware could only shift by one.
* mask the shift (likely `a & (globalmasksize-1)`, although the mask the hardware uses might be larger than the programmer's idea of the variable's width - consider a platform that *only* has 32-bit registers). This is the common result today.

`ror` doesn't care *which* choice (it's either `b | b` or `b | 0`), but the choice has to be made (or do both and have a way to select which is active).

***

For division and modulo, remember the 2 invariants:

```python
q = n / d
r = n % d
assert d*q + r == n
assert -abs(d) < r < abs(d)
```

We can further choose only one of:

```python
assert -(n/d) == (-n)/d
if d > 0: assert 0 <= r
```

Here's a useful table, supposing 8-bit math.

flavor   |  n  |  d  |  q  |  r
---------|-----|-----|-----|-----
unsigned |  10 |   3 |   3 |   1
unsigned |  10 |  -3 |   0 |  10
unsigned | -10 |   3 |  82 |   0
unsigned | -10 |  -3 |   0 | -10
round to 0, sign of r follows n |  10 |   3 |   3 |   1
round to 0, sign of r follows n |  10 |  -3 |  -3 |   1
round to 0, sign of r follows n | -10 |   3 |  -3 |  -1
round to 0, sign of r follows n | -10 |  -3 |   3 |  -1
round to -∞, sign of r follows d |  10 |   3 |   3 |   1
round to -∞, sign of r follows d |  10 |  -3 |  -4 |  -2
round to -∞, sign of r follows d | -10 |   3 |  -4 |   2
round to -∞, sign of r follows d | -10 |  -3 |   3 |  -1

I also [wrote some quick code](https://gist.github.com/o11c/5217c9a0350b4379232210e19acc8ae5)

**Comment by alt-romes** [comment]
I've added the part of the division and modules flavour to another issue #47 
With that, I think all things todo in the time being are either already done or in a separate issue
